-- Таблица №1. Непокрытые внутроссийские аккредитивы.
create table RU_LC
(
GOSB_ID  VARCHAR2(100),
DATE_OF_CONCLUSION  DATE  not null,
PRODUCT VARCHAR2(100),
NAME_OF_THE_CLIENT VARCHAR2(100),
CURRENCY VARCHAR2(5),
VOLUME_NKD NUMBER(30) not null,
MANAGER VARCHAR2(100)
)
/

-- Таблица №2. Международные аккредитивы.
create table int_LC
(
GOSB_ID  VARCHAR2(100),
DATE_OF_CONCLUSION  DATE  not null,
PRODUCT VARCHAR2(100),
NAME_OF_THE_CLIENT VARCHAR2(100),
CURRENCY VARCHAR2(5),
VOLUME_NKD NUMBER(30) not null,
MANAGER VARCHAR2(100)
)
/

-- Таблица №3. Покрытые аккредитивы ВРА
create table cove_LC
(
GOSB_ID  VARCHAR2(100),
DATE_OF_CONCLUSION  DATE  not null,
PRODUCT VARCHAR2(100),
NAME_OF_THE_CLIENT VARCHAR2(100),
CURRENCY VARCHAR2(5),
VOLUME_NKD NUMBER(30) not null,
MANAGER VARCHAR2(100)
)
